### ISSUE TITLE
Improving Button's UI inside Insert Clause Template 

### ISSUE THREAD

**Issue by arteevraina** [accordproject/cicero-word-add-in-deprecated#109]
![image](https://user-images.githubusercontent.com/43968121/78062190-e95cdb00-73ab-11ea-85f0-b8924035d736.png)

I want to work on this issue :)

**Comment by nik72619c** [comment]
@arteevraina I am not sure if this is an issue at the moment since the buttons seem okay to me but I might be wrong too. Would love to hear @DianaLease and @dselman 's thoughts on it :)

**Comment by DianaLease** [comment]
I think @Michael-Grover would be best to speak on this.

**Comment by Michael-Grover** [comment]
@arteevraina Can you elaborate on what the issue is?

**Comment by arteevraina** [comment]
@Michael-Grover I think that UI of these `Text` buttons can be improved. `Text` Buttons are used for those actions which are less pronounced in an application but as per my opinion these buttons play a very important role in Cicero-Word-Add-in. UI can be in following ways:

- By making them `Outlined Buttons`.
- By making them `Contained Buttons`.

But, I would love to have your opinion on this.

**Comment by Michael-Grover** [comment]
@arteevraina I can't see the context that these buttons are in, so I am going to try to get the word add-in running on my machine so I can give better feedback

**Comment by arteevraina** [comment]
@Michael-Grover Can you give me your feedback on this?

**Comment by Michael-Grover** [comment]
sure let's make these contained buttons

**Comment by arteevraina** [comment]
@Michael-Grover Sure, I will send a PR a shortly.
