### ISSUE TITLE
Clauseid and Templateid text going out of task-pane size.

### ISSUE THREAD

**Issue by arteevraina** [accordproject/cicero-word-add-in-deprecated#130]
If we enter a long `ClauseId` and `TemplateId `. The Smart Clause List when displays it goes out of task pane size and text overlaps `delete` icon.

![image](https://user-images.githubusercontent.com/43968121/79045495-0c4b8280-7c29-11ea-871b-1856def9f693.png)
This is a zoomed image but we are having same issue in normal zoom.
Would Like to have your views on this @Michael-Grover @DianaLease

**Comment by DianaLease** [comment]
This should probably wrap instead. What do you think @Michael-Grover ?

**Comment by Michael-Grover** [comment]
yeah I agree it should wrap @DianaLease
