### ISSUE TITLE
The input text is white

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-word-add-in-deprecated#35]
#### Description
The color of the text inside the main input is white. The text can be seen when highlighted as shown :-

<img width="376" alt="Screenshot 2020-03-18 at 12 12 28 AM" src="https://user-images.githubusercontent.com/30630904/76890411-54d38280-68ad-11ea-8280-b65722df73e4.png">

OS :- MacOS Cataline (v10.15.2)

**Comment by nik72619c** [comment]
@dselman @DianaLease Are you able to reproduce it ?

**Comment by dselman** [comment]
Yes.

**Comment by nik72619c** [comment]
@dselman Shall I start working on this then ?

**Comment by nik72619c** [comment]
@dselman let me know your thoughts on this:-
ref #36
