### ISSUE TITLE
Dialog persist state even after closing

### ISSUE THREAD

**Issue by shakti2379** [accordproject/cicero-word-add-in-deprecated#37]
New Smart clause dialog preserving the state of the text box

Steps to Reproduce:
1. Go to Create New Smart Clause .
2. Enter Clause Id and Template Id.
3. Close the dialog by clicking on Ok or Cancel
4. Now go to create New Smart Clause Again you will see the text you previously entered.

**Comment by arteevraina** [comment]
@shakti2379 can i work on this issue ?

**Comment by shakti2379** [comment]
I am working on this
Thanks

**Comment by arteevraina** [comment]
okay np
