### ISSUE TITLE
clause template list is missing loading spinner

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-word-add-in-deprecated#39]
#### Description 
Currently, the list which displays the clause templates list does not have a fallback UI or a spinner. Steps to reproduce the issue:-
1. Sideload the cicero-UI add-in
2. switch over to the `Templates ` tab
3. The list is a blank component first and then the list appears

OS details:- 
Mac OS Catalina (v10.15.2)

**Comment by nik72619c** [comment]
@dselman @DianaLease  Are you able to reproduce this issue ?

**Comment by DianaLease** [comment]
> @dselman @DianaLease Are you able to reproduce this issue ?

yes, a loader would be nice here
