### ISSUE TITLE
Add cicero logo svg in react webpage

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-word-add-in-deprecated#97]
#### Description

The `cicero` logo was added in the word add-in based on the decisions taken with @Michael-Grover. The react webpage which can be seen on opening the project on the browser and visiting `localhost:3000` should also have the same logo.

OS config:- Mac OS Catalina(v10.12.0)

**Comment by nik72619c** [comment]
@DianaLease @dselman let me know if I should go forward with the fix for it?

**Comment by nik72619c** [comment]
@DianaLease @Michael-Grover any thoughts on this ?

**Comment by Michael-Grover** [comment]
@nik72619c can you include screenshots please?

**Comment by nik72619c** [comment]
yup, working on it.

**Comment by nik72619c** [comment]
<img width="1038" alt="Screenshot 2020-04-05 at 11 36 52 PM" src="https://user-images.githubusercontent.com/30630904/78506324-78943500-7796-11ea-9f4e-9c3dd1eb1a6f.png">

@Michael-Grover

**Comment by Michael-Grover** [comment]
[Cicero-black.svg.zip](https://github.com/accordproject/cicero-word-add-in/files/4439165/Cicero-black.svg.zip)
Can we use the above Cicero logo and this Accord Project logo:

[accord project.svg.zip](https://github.com/accordproject/cicero-word-add-in/files/4439171/accord.project.svg.zip)

**Comment by nik72619c** [comment]
Yup, I am working on that.

**Comment by nik72619c** [comment]
<img width="1280" alt="Screenshot 2020-04-06 at 9 36 12 PM 1" src="https://user-images.githubusercontent.com/30630904/78579509-adfc5980-784e-11ea-8005-22f1b596aa8e.png">

@Michael-Grover @DianaLease

**Comment by Michael-Grover** [comment]
Looks great, can we add an extra 100px between "Cicero Word Add-in",  the AP logo, and the final line of text? They look a bit squished right now.

**Comment by nik72619c** [comment]
makes sense !

**Comment by nik72619c** [comment]
<img width="1280" alt="Screenshot 2020-04-06 at 9 53 24 PM" src="https://user-images.githubusercontent.com/30630904/78581119-10eef000-7851-11ea-81fb-3f287fb18ffa.png">

**Comment by nik72619c** [comment]
@Michael-Grover does it look good now?

**Comment by Michael-Grover** [comment]
yeah it looks good to me, thanks. Can you make a PR I can review?

**Comment by nik72619c** [comment]
done @Michael-Grover
